### ISSUE TITLE
missing map folder and files

### ISSUE THREAD

**Issue by msalaciak** [ZJUFanLab/scDeepSort#1]
Hi, installed and trying to run the example provided but we are missing the map folder as it was not included in the git repo. Where can we find this? 

Thanks!

**Comment by shaoxin0801** [comment]
Sorry for getting back to you so late. The manuscript is under major revision and we have to optimize our method. The map folder has been uploaded.

**Comment by msalaciak** [comment]
No problem, thank you and good luck with the revisions!
