### ISSUE TITLE
Learnable sharing parameter Beta

### ISSUE THREAD

**Issue by xiaoyanLi629** [ZJUFanLab/scDeepSort#13]
Hello,

In the paper, aggregation process, it says there is a learnable sharing parameter beta. I didn't see beta in the code. Are you using another name for this parameter?

Thank you!

**Comment by RamonYeung** [comment]
Sorry for the late reply. We summarize alpha and beta into one parameter for efficient computation. Please check this out.

Let me know if you have further questions!

Thanks for your attention.
