### ISSUE TITLE
Edges for testing

### ISSUE THREAD

**Issue by xiaoyanLi629** [ZJUFanLab/scDeepSort#14]
Hello,

I noticed in the training process, the graph was constructed by adding edges (gene to cell) and (cell to gene) and self-loop.

However, in testing, I found the edges are original training edges ((gene to cell) and (cell to gene) and self-loop in training) plus (gene to test cell) and test cell self-loop. The test cell to gene edges ar missing. So I am wondering, is there a reason for this?

Or I misunderstand the code?

Thank you!

**Comment by toooooodo** [comment]
Your understand is right. 
Actually on the test stage, there are two parts in the graph: 1. genes and training cells, 2. testing cells. The model is trained on the first part, and we want to leverage the information in the first part (training stage) to the second part (testing stage). So we only add edges from genes to testing cells. If adding edges from testing cells to genes, the message from testing cells will be mixed into message passing process in the model and it maybe hurt the reference result.
