### ISSUE TITLE
Pytorch 1.6.0 installation fails

### ISSUE THREAD

**Issue by mariokreutzfeldt** [ZJUFanLab/scDeepSort#15]
Hello,

I am trying to setup scDeepSort using CUDA 10.2.
I've downloaded scDeepSort-v1.0-cu102.tar.gz but when I install it via pip, I get the error:
`Could not find a versionthat satisfies the requirement torch==1.6.0`

I have tried python versions 3.9.7, 3.8.6, 3.8.0 and 3.7.0. All lead to the same error.
The lowest version I managed to install was 1.7.1 but this only installed the CPU version, even though I followed the official pytorch installation instructions (and CUDA 10.2 is correctly installed).

So my questions are the following:
- Is scDeepSort compatible with newer pytorch versions?
- Which python version is recommended to install torch==1.6.0?

Thank you and best regards,
Mario

**Comment by shaoxin0801** [comment]
You can try use conda to install, refer to https://pytorch.org/get-started/locally/
