### ISSUE TITLE
What is a supported version?

### ISSUE THREAD

**Issue by ivy-yuan** [ZJUFanLab/scDeepSort#21]
I downloaded and installed scDeepSort-v1.0-cpu.tar.gz as described but encoutered an error that tensorflow 2.4.0 is not supported. I tried tensorflow 2.3.0 but the numpy version was not compatible though I tried kinds of versions from 1.16.0 to 1.21.0. Also,  tensorflow 2.2.0 was not available with the error `AttributeError: module 'tensorflow' has no attribute '__version__'` .Could anyone help me with this issue?

**Comment by shaoxin0801** [comment]
Hello, python3.7.6 with pytorch is supported for scDeepSort-v1.0-cpu.tar.gz in my system.
