### ISSUE TITLE
how to save my own model?

### ISSUE THREAD

**Issue by Ldabao233** [ZJUFanLab/scDeepSort#24]
Hi, Xin Shao!
    Could you tell me how to save my own training model? So that, when I use the model next time, I don't need re-run the "fit" step （it takes too long😧), just running the "model.predict".
    Thanks!!!

**Comment by multitalk** [comment]
Hello, the model is stored in `pretrianed/human` or `pretrianed/mouse` when you use `fit`. You can use tissue name like `liver1`, `liver2` as the re-trained model to avoid the repeat in the pretrained models in  `pretrianed/human` and `pretrianed/mouse`.

**Comment by Ldabao233** [comment]
Thanks for your reply! I predicted using the pretrained model, it work✌️
