### ISSUE TITLE
Deepsort problem

### ISSUE THREAD

**Issue by 20221051** [ZJUFanLab/scDeepSort#25]
Hi, Xin Shao!

I have three problems in running scDeepsort

First, if data has less than 400 cells, PCA error is occured. How can I solve it ?

Second, In my own prediction in human_pancreas_data, Cell_type data has alpha, beta, delta etc.
But original label is Alpha cell, Beta cell, Delta cell. So my own acc is 0. 
In this case, Do I suucess prediction?

Last,  Can I get a based reference or standard of mapping file?

**Comment by multitalk** [comment]
Hello, you can refer to the mapping file https://github.com/ZJUFanLab/scDeepSort/blob/master/map/celltype2subtype.xlsx

**Comment by 20221051** [comment]
First of all thanks for the reply.

I already checked the celltype2subtype file. However, what I was curious about was when mapping the training and test files, whether it is possible to map all subtypes of the celltype. When I ran the model, there were cases such as original label: proximal tubule cell, pred: tubule cell. But it didn't exist in the mapping file. Therefore, I wondered what criteria this mapping file was created and whether intuitively similar celltypes could be mapped.

Thank you.

**Comment by multitalk** [comment]
Thanks for your question. In fact, the celltype2subtype file was created mainly according to the Cell-Ontology, knowledge from literature. You can create a custom  celltype2subtype file. For some cell types without known subtypes, you can regard cell type as subtype as the example below. For your own trained datasets, you must change the  celltype2subtype file to ensure that all cell types have the corresponding subtypes for training.
|celltype|subtype|
|---|---|
|Podcyte|Podcyte|
