### ISSUE TITLE
The impact of different inputs on the prediction outcome

### ISSUE THREAD

**Issue by BioLaoXu** [ZJUFanLab/scDeepSort#26]
Hi，scDeepSort team,using GNN for cell type indentify is a pretty cool work. But after analyzing by the scDeepSort in my dataset, I had one confusions: 
my data have 0.2M(200000) cells,scDeepSort's computation is very slow,may be scDeepSort need use all cells to build graph,After running ~12h and still not finishing, I finally gave up(CPU version).Therefore,I perform cell subtype identification for each cluster cells,and cell subtype identification by clusters cells alone greatly increases speed，But I doubt that this will lose the global cell subtype information.

**Comment by multitalk** [comment]
Hello, I think you are right since the test sample will perform PCA. So size of sampls, namely the number of test cells each time, might influence the prediction. You might try several clusters each time or find a larger server.
