### ISSUE TITLE
About the setting of beta

### ISSUE THREAD

**Issue by gerrardmai** [ZJUFanLab/scDeepSort#3]
I have read the preview paper and found that was a pretty cool method to do classification.

But I have one questions, about the setting of learnable sharing parameter beta;
it that the fixed-parameter or need to calculated by another formula? 
will it updated during the iteration?

**Comment by ZJUFanLab** [comment]
Yes, the learnable sharing parameters including beta will be updated during the iteration.

**Comment by gerrardmai** [comment]
another question, 
there are three main parts in the scDeepSort.
are the weighted aggregator layer part and linear classifier layer independent?  
In my understanding, the second part is used to generate the new input of part three. 
How the sharing parameter beta updated after each epoch of linear classifier?

Thank you for your reply.
