### ISSUE TITLE
how to train my own model.

### ISSUE THREAD

**Issue by gerrardmai** [ZJUFanLab/scDeepSort#6]
How to train my own model?

I followed the preprocess script to created the .gz data (gene*cells ) and celltype table into csv (Celltype name is denifited by me) 

then I put them into "mouse" file  and the issue names is "project1" 

But I get the information below:

**The build graph contains 4944 genes with 0 labels supported.** (there are 224 celltype labels)

I also find that there are not only 4 labels in file "human_Adipose1372_celltype"  But why the information showed is :

**The build graph contains 16397 genes with 4 labels supported.
human_Adipose3_data.gz -> Nonzero Ratio: 2.75%
Added 1354 nodes and 610321 edges.
#Nodes in Graph: 17751, #Edges: 1220642.
[PCA] Gene EVR: 66.25 %.
------Train label statistics------
#1 [Stromal cell]: 184
#2 [Macrophage]: 1099
#3 [Monocyte]: 18
#4 [Fibroblast]: 53**

is the label information included into .gz file?

**Comment by shaoxin0801** [comment]
The cell type table (.csv) should be like this as the example of [`mouse_Muscle1102_celltype.csv`](https://github.com/ZJUFanLab/scDeepSort/blob/dev/train/mouse/mouse_Muscle1102_celltype.csv)
