### ISSUE TITLE
Repeated Training, wrong number of different celltypes

### ISSUE THREAD

**Issue by Onero23** [ZJUFanLab/scDeepSort#7]
Hi,
Doing repeated training on different training sets will delete previous trained models. Is there a workaround?
During training only about 25% of different celltypes are recognized as unique cell types no matter how many features are included (100 genes, 1000 genes,10000 genes, etc.). Is there a maxium of unique celltypes accepted during the training process?
Thanks a lot!

**Comment by gerrardmai** [comment]
Try to set  exclude_rate to 0 in train.py, may solve your problem.
parser.add_argument("--exclude_rate", type=float, default=0,help="exclude some cells less than this rate.")

**Comment by Onero23** [comment]
Thank you very much, this solved the problem!
